openai_api_base: https://vip.apiyi.com/v1

openai_api_key: sk-5PYQRpTeWXyM9ibd96B5737aFdCc47B1B89a3937F6447eEe

tmdb_access_token: gasdg

spotipy_client_id: gasdg
spotipy_client_secret: gasgd
spotipy_redirect_uri: gasdg


scenario: gitlab_difficult
index: 6
query: "First, create a new branch named 'testBranch' based on the 'main' branch on the GitLab repository with ID 68772011. Then, delete the branch."