openai_api_base: https://vip.apiyi.com/v1

openai_api_key: sk-5PYQRpTeWXyM9ibd96B5737aFdCc47B1B89a3937F6447eEe

tmdb_access_token: gasdg

spotipy_client_id: gasdg
spotipy_client_secret: gasgd
spotipy_redirect_uri: gasdg


scenario: gitlab_en
index: 5
query: "How many pending invitations are there currently in the GitLab group with ID 97683359?"