openai_api_base: https://vip.apiyi.com/v1

openai_api_key: sk-5PYQRpTeWXyM9ibd96B5737aFdCc47B1B89a3937F6447eEe

tmdb_access_token: gasdg

spotipy_client_id: gasdg
spotipy_client_secret: gasgd
spotipy_redirect_uri: gasdg


scenario: docker_en
index: 7
query: Query the logs of the docker container named 'jenkins' and return the details of the last log entry.